CREATE DATABASE PROD;
USE PROD;
CREATE TABLE IF NOT EXISTS NEWS_SITE (
Id INT AUTO_INCREMENT,
ARTICLE_DATE DATE NOT NULL,
CATEGORY VARCHAR(100),
WEBSITE VARCHAR(100),
NAME VARCHAR(1000),
URL VARCHAR(1000),
BRIEF VARCHAR(1000),
PICTURE VARCHAR(1000),
PRIMARY KEY (id)
);